### ISSUE TITLE
Losing wallet connection

### ISSUE THREAD

**Issue by lovesushi5** [ociswap/feedback#1]
meow-y schlimm

**Comment by Bowoaan** [comment]
I've tried swap and the transaction is very fast I like it very much, and just having a little problem when connecting and sometimes the "transaction submitted" notification doesn't appear, I'm using android and the extension on the kiwi browser, thank you for giving the opportunity

**Comment by Bowoaan** [comment]
![Screenshot_2022-08-01-10-16-09-228_com android chrome](https://user-images.githubusercontent.com/99853033/182066204-57af3718-1746-4ee3-af6a-7aa0d69ef339.jpg)
![Screenshot_2022-08-01-10-07-54-384_com kiwibrowser browses](https://user-images.githubusercontent.com/99853033/182066975-efcc52fb-4b81-497a-b5f6-60ffd0e425d1.jpg)


And wallet zeus transaction so fast i like this very fast until I submitted it 2 times and it turned out that the first transaction was successfully swapped, only sometimes on ociswap there is no "transaction submitted" notification

**Comment by MatheusPiva14** [comment]
First of all congratulations on the team work!! For the tests I used Google Chrome, I managed to do several swaps, all were successful and very fast. My only problem was when carrying out the swap, the wallet disconnected from Ociswap, and I had to connect again, but everything was ok with the transaction. I will continue testing and reporting here in case any bugs appear.

**Comment by fpieper** [comment]
@MatheusPiva14 thank you very much for your feedback. The connection issues will be solved with the next Z3US wallet update (already in review by Google). I tried with the Z3US preview locally and it worked fine now in Chrome.

If you like you can try it in Firefox - there the new Z3US wallet is already available and you your connection issues will be fixed 👍 .

**Comment by fpieper** [comment]
@Bowoaan thank you, the connection issues in Kiwi should also solved with the upcoming Z3US update in the Chrome store.

It then is also not possible anymore to submit/approve the same transaction twice in the wallet. So, good things ahead 💯

**Comment by MatheusPiva14** [comment]
Wonderful, I will also test in FireFox and again in Chrome. I really enjoyed it, congratulations guys!
